language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - npm run build:css
  - npm run lint
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: 
    master: u-tictactoe
    dev: u-tictactoe-dev
  skip_cleanup: true